// design/orrery/project/backlog.jsx
/* global React, Icon, StatusDot, ToolBadge, STATUS_META, projectOf, ORG, Tag, TagFilter */
// ── Backlog — integrated Orchestrator view (board + cards) ──────────────────
const { useState: useStateBL } = React;

const TICKET_COL = {
  todo:       { key: "todo",       label: "To do",       color: "var(--ink-3)" },
  inprogress: { key: "inprogress", label: "In progress", color: "var(--accent)" },
  done:       { key: "done",       label: "Done",        color: "var(--st-done)" },
};
const TICKET_ORDER = ["todo", "inprogress", "done"];

const _plainCache = {};
function plainText(html) {
  if (html == null) return "";
  if (_plainCache[html]) return _plainCache[html];
  const d = document.createElement("div"); d.innerHTML = html;
  const t = (d.textContent || "").replace(/\s+/g, " ").trim();
  _plainCache[html] = t; return t;
}

// ── ticket project chip ──────────────────────────────────────────────────────
function TicketChip({ projectId, muted }) {
  const p = projectOf(projectId);
  if (!p) return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, color: "var(--ink-4)" }}>
      <Icon name="folder" size="sm" style={{ width: 11, height: 11, flex: "none" }} />no project
    </span>
  );
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, minWidth: 0, overflow: "hidden", color: muted ? "var(--ink-3)" : p.color }}>
      <Icon name={p.icon} size="sm" style={{ width: 12, height: 12, flex: "none" }} />
      <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{p.name}</span>
    </span>
  );
}

// ── attached live-agent strip (resolves the real agent's status) ─────────────
function AgentStrip({ agent, onOpen }) {
  const m = STATUS_META[agent.status] || STATUS_META.idle;
  const [hover, setHover] = useStateBL(false);
  return (
    <div onClick={(e) => { e.stopPropagation(); onOpen(agent.id); }}
      onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}
      title="Open agent workspace"
      style={{ display: "flex", flexDirection: "column", gap: 7, padding: "8px 9px", cursor: "pointer", borderRadius: "var(--r-md)",
        background: "var(--panel-2)", border: "1px solid " + (hover ? "color-mix(in oklch, " + m.color + ", transparent 55%)" : "var(--hair)"),
        boxShadow: hover ? "0 0 0 1px color-mix(in oklch, " + m.color + ", transparent 72%)" : "none", transition: "border-color .15s, box-shadow .15s" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 7, minWidth: 0 }}>
        <ToolBadge tool={agent.tool} size={17} />
        <span className="disp" style={{ fontSize: 12, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", flex: "0 1 auto" }}>{agent.name}</span>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 5, flex: "none", fontSize: 9.5, padding: "2px 7px 2px 6px", borderRadius: 999,
          letterSpacing: ".08em", textTransform: "uppercase", color: m.color,
          border: "1px solid color-mix(in oklch, " + m.color + ", transparent 62%)", background: "color-mix(in oklch, " + m.color + ", transparent 88%)" }}>
          <StatusDot status={agent.status} />{m.label}
        </span>
        <Icon name="enter" size="sm" style={{ marginLeft: "auto", flex: "none", color: hover ? m.color : "var(--ink-4)", transition: "color .15s" }} />
      </div>
      <div style={{ height: 3, borderRadius: 3, background: "var(--hair)", overflow: "hidden", position: "relative" }}>
        <div style={{ height: "100%", width: Math.max((agent.progress || 0) * 100, 4) + "%", borderRadius: 3,
          background: m.color, opacity: agent.status === "blocked" ? 0.5 : 1, transition: "width .6s ease" }} />
        {agent.status === "running" && <div className="activity" style={{ position: "absolute", inset: 0, background: "transparent" }} />}
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 10, color: "var(--ink-3)" }} className="tnum">
        {agent.status === "blocked" && agent.blockReason
          ? <span style={{ display: "flex", alignItems: "center", gap: 5, color: "var(--code-del-ink)", minWidth: 0 }}>
              <Icon name="flag" size="sm" style={{ width: 11, height: 11, flex: "none" }} />
              <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{agent.blockReason}</span></span>
          : <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{agent.branch.replace("agent/", "")}</span>}
        <span style={{ marginLeft: "auto", display: "flex", gap: 4, flex: "none", color: "var(--ink-4)" }}>
          <Icon name="commit" size="sm" style={{ width: 11, height: 11 }} />{agent.commits}</span>
      </div>
    </div>
  );
}

// ── ticket card ──────────────────────────────────────────────────────────────
function TicketCard({ ticket, agents, onOpen, onDispatch, onOpenAgent, onDragStart, onDragEnd, dragging, activeTags, onToggleTag }) {
  const [hover, setHover] = useStateBL(false);
  const st = ticket.status;
  const agent = ticket.agentId ? agents.find((a) => a.id === ticket.agentId) : null;

  const wrap = {
    background: "var(--panel)", border: "1px solid var(--hair)", borderRadius: "var(--r-lg)", padding: 13,
    display: "flex", flexDirection: "column", gap: 9, position: "relative", cursor: "pointer",
    transition: "border-color .15s, transform .15s, box-shadow .15s",
    ...(st === "inprogress" ? { borderLeft: "2px solid color-mix(in oklch, var(--accent), transparent 35%)" } : {}),
    ...(st === "done" ? { background: "var(--panel-2)" } : {}),
    ...(hover ? { borderColor: "var(--hair-2)", transform: "translateY(-2px)", boxShadow: "var(--shadow)" } : {}),
    ...(dragging ? { opacity: 0.4 } : {}),
  };

  return (
    <div draggable onDragStart={(e) => onDragStart(e, ticket)} onDragEnd={onDragEnd}
      onClick={() => onOpen(ticket.id)} onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)} style={wrap}>
      <div style={{ display: "flex", alignItems: "flex-start", gap: 8 }}>
        {st === "done" && (
          <span style={{ flex: "none", width: 16, height: 16, marginTop: 1, borderRadius: "50%", display: "grid", placeItems: "center",
            background: "color-mix(in oklch, var(--st-done), transparent 82%)", border: "1px solid color-mix(in oklch, var(--st-done), transparent 55%)" }}>
            <Icon name="check" size="sm" style={{ width: 11, height: 11, color: "var(--st-done)" }} />
          </span>
        )}
        <span className="disp" style={{ fontSize: 13.5, fontWeight: 600, lineHeight: 1.3, flex: 1, minWidth: 0,
          display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden",
          color: st === "done" ? "var(--ink-2)" : "var(--ink)" }}>{ticket.title}</span>
        <span style={{ flex: "none", fontSize: 9.5, color: "var(--ink-4)", marginTop: 2 }} className="tnum">#{ticket.id.replace(/^t/, "")}</span>
      </div>

      {st !== "done" && <p style={{ fontSize: 12, color: "var(--ink-2)", lineHeight: 1.5,
        display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" }}>{plainText(ticket.notes)}</p>}

      {(ticket.tags && ticket.tags.length > 0) && (
        <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
          {ticket.tags.map((t) => <Tag key={t} name={t} active={activeTags && activeTags.includes(t)} onClick={onToggleTag} />)}
        </div>
      )}

      {st === "inprogress" && (agent
        ? <AgentStrip agent={agent} onOpen={onOpenAgent} />
        : <div onClick={(e) => { e.stopPropagation(); onDispatch(ticket); }}
            style={{ display: "flex", alignItems: "center", gap: 7, padding: "7px 9px", borderRadius: "var(--r-md)", cursor: "pointer",
              border: "1px dashed color-mix(in oklch, var(--accent), transparent 55%)", color: "var(--accent)", fontSize: 11 }}>
            <Icon name="bolt" size="sm" />No agent yet — dispatch one</div>)}

      {st === "todo" && (
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <TicketChip projectId={ticket.projectId} />
          <button className={"btn " + (hover ? "primary" : "ghost-hair")} onClick={(e) => { e.stopPropagation(); onDispatch(ticket); }}
            style={{ marginLeft: "auto", flex: "none", padding: "5px 11px", fontSize: 11.5,
              ...(hover ? {} : { color: "var(--accent)", borderColor: "color-mix(in oklch, var(--accent), transparent 55%)" }) }}>
            <Icon name="bolt" size="sm" />Dispatch</button>
        </div>
      )}
      {st === "inprogress" && <div style={{ display: "flex", alignItems: "center" }}><TicketChip projectId={ticket.projectId} /></div>}
      {st === "done" && (
        <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 11, color: "var(--ink-3)" }} className="tnum">
          <TicketChip projectId={ticket.projectId} muted />
          {agent && <span style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 6, flex: "none" }}>
            <ToolBadge tool={agent.tool} size={14} />
            <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 92 }}>{agent.name}</span>
            <span style={{ color: "var(--ink-4)" }}>·</span>
            <span style={{ display: "flex", alignItems: "center", gap: 3, color: "var(--st-done)" }}>
              <Icon name="commit" size="sm" style={{ width: 11, height: 11 }} />{agent.commits}</span>
          </span>}
        </div>
      )}
    </div>
  );
}

// ── board column (drop target) ───────────────────────────────────────────────
function Column({ status, tickets, agents, onOpen, onDispatch, onOpenAgent, onMove, drag, setDrag, onNew, activeTags, onToggleTag }) {
  const m = TICKET_COL[status];
  const [over, setOver] = useStateBL(false);
  const isTarget = drag && drag.from !== status;

  return (
    <div onDragOver={(e) => { if (drag) { e.preventDefault(); setOver(true); } }}
      onDragLeave={() => setOver(false)}
      onDrop={(e) => { e.preventDefault(); if (drag) onMove(drag.id, status); setOver(false); }}
      style={{ display: "flex", flexDirection: "column", gap: 9, minWidth: 0, borderRadius: "var(--r-lg)",
        outline: over && isTarget ? "1.5px dashed color-mix(in oklch, " + m.color + ", transparent 35%)" : "1.5px dashed transparent",
        outlineOffset: 4, background: over && isTarget ? "color-mix(in oklch, " + m.color + ", transparent 94%)" : "transparent", transition: "background .15s" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "0 2px 6px", borderBottom: "2px solid " + m.color, flex: "none" }}>
        <span className="up" style={{ fontSize: 10, color: "var(--ink-2)" }}>{m.label}</span>
        <span className="chip tnum" style={{ marginLeft: "auto", fontSize: 9.5, padding: "0 6px" }}>{tickets.length}</span>
      </div>
      {tickets.map((tk) => (
        <TicketCard key={tk.id} ticket={tk} agents={agents} onOpen={onOpen} onDispatch={onDispatch} onOpenAgent={onOpenAgent}
          dragging={drag && drag.id === tk.id} activeTags={activeTags} onToggleTag={onToggleTag}
          onDragStart={(e, t) => { setDrag({ id: t.id, from: t.status }); try { e.dataTransfer.effectAllowed = "move"; e.dataTransfer.setData("text/plain", t.id); } catch (_) {} }}
          onDragEnd={() => { setDrag(null); setOver(false); }} />
      ))}
      {status === "todo" && (
        <button className="btn" onClick={onNew} style={{ justifyContent: "center", gap: 6, padding: 9, borderRadius: "var(--r-md)",
          border: "1px dashed var(--hair-2)", color: "var(--ink-3)", fontSize: 11.5, background: "transparent" }}>
          <Icon name="plus" size="sm" />New ticket</button>
      )}
      {!tickets.length && status !== "todo" && (
        <div style={{ padding: 14, textAlign: "center", color: "var(--ink-4)", fontSize: 10.5, border: "1px dashed var(--hair)", borderRadius: "var(--r-md)" }}>empty</div>
      )}
    </div>
  );
}

// ── the Backlog view (center pane) ───────────────────────────────────────────
function BacklogView({ tickets, agents, projects, allTags, onOpen, onNew, onDispatch, onOpenAgent, onMove }) {
  const [filter, setFilter] = useStateBL("all");
  const [filterOpen, setFilterOpen] = useStateBL(false);
  const [tagSel, setTagSel] = useStateBL([]);
  const [drag, setDrag] = useStateBL(null);

  const tags = allTags || [];
  const tagCounts = {};
  tickets.forEach((t) => (t.tags || []).forEach((tg) => { tagCounts[tg] = (tagCounts[tg] || 0) + 1; }));
  // keep the filter from holding tags that no longer exist anywhere
  const activeTagSel = tagSel.filter((t) => tags.includes(t));
  const toggleTag = (t) => setTagSel((s) => s.includes(t) ? s.filter((x) => x !== t) : [...s, t]);

  const shown = tickets.filter((t) =>
    (filter === "all" || t.projectId === filter) &&
    (activeTagSel.length === 0 || (t.tags || []).some((tg) => activeTagSel.includes(tg)))
  );
  const open = tickets.filter((t) => t.status !== "done").length;
  const filterName = filter === "all" ? "All projects" : (projectOf(filter) || {}).name;
  const isEmpty = tickets.length === 0;

  return (
    <div style={{ display: "flex", flexDirection: "column", minHeight: 0, background: "var(--panel-2)" }}>
      {/* header */}
      <div style={{ display: "flex", alignItems: "center", gap: 14, padding: "14px 18px", flex: "none", borderBottom: "1px solid var(--hair)", background: "var(--panel)" }}>
        <div>
          <h1 className="disp" style={{ fontSize: 16, fontWeight: 600, letterSpacing: "-0.02em" }}>Backlog</h1>
          <span style={{ fontSize: 10.5, color: "var(--ink-3)" }}>{tickets.length} tickets · {open} open · {ORG}</span>
        </div>
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ position: "relative" }}>
            <button className="btn ghost-hair" style={{ fontSize: 11.5, color: "var(--ink-2)" }} onClick={() => setFilterOpen((o) => !o)}>
              <Icon name="folder" size="sm" style={{ color: "var(--ink-3)" }} />{filterName}
              <Icon name="chevronD" size="sm" style={{ color: "var(--ink-4)" }} />
            </button>
            {filterOpen && (
              <div className="surface" style={{ position: "absolute", top: "100%", right: 0, marginTop: 6, zIndex: 20, padding: 5, minWidth: 190, boxShadow: "var(--shadow)" }}>
                {[{ id: "all", name: "All projects" }, ...projects].map((p) => (
                  <div key={p.id} onClick={() => { setFilter(p.id); setFilterOpen(false); }}
                    style={{ display: "flex", alignItems: "center", gap: 8, padding: "7px 9px", borderRadius: "var(--r-sm)", cursor: "pointer", fontSize: 12,
                      background: filter === p.id ? "var(--panel-3)" : "transparent", color: filter === p.id ? "var(--ink)" : "var(--ink-2)" }}
                    onMouseEnter={(e) => { if (filter !== p.id) e.currentTarget.style.background = "var(--panel-2)"; }}
                    onMouseLeave={(e) => { if (filter !== p.id) e.currentTarget.style.background = "transparent"; }}>
                    {p.id === "all" ? <Icon name="layers" size="sm" style={{ color: "var(--ink-3)" }} /> : <Icon name={p.icon} size="sm" style={{ color: p.color }} />}
                    {p.name}
                  </div>
                ))}
              </div>
            )}
          </div>
          <TagFilter allTags={tags} counts={tagCounts} selected={activeTagSel} onChange={setTagSel} />
          <button className="btn primary" onClick={onNew}><Icon name="plus" size="sm" />New ticket</button>
        </div>
      </div>

      {/* active tag-filter summary */}
      {activeTagSel.length > 0 && (
        <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "9px 18px", flex: "none", borderBottom: "1px solid var(--hair)", background: "var(--panel)" }}>
          <span className="up" style={{ fontSize: 9.5, color: "var(--ink-4)", letterSpacing: ".1em", flex: "none" }}>Filtered by</span>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {activeTagSel.map((t) => <Tag key={t} name={t} active onRemove={(n) => toggleTag(n)} />)}
          </div>
          <span style={{ marginLeft: "auto", flex: "none", fontSize: 10.5, color: "var(--ink-4)" }} className="tnum">{shown.length} of {tickets.length}</span>
        </div>
      )}

      {/* body */}
      <div className="scroll-y" style={{ flex: 1 }}>
        {isEmpty ? (
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 14, padding: "80px 20px", textAlign: "center" }}>
            <div style={{ width: 52, height: 52, borderRadius: 14, display: "grid", placeItems: "center",
              background: "color-mix(in oklch, var(--accent), transparent 88%)", border: "1px solid color-mix(in oklch, var(--accent), transparent 60%)" }}>
              <Icon name="layers" size="lg" style={{ color: "var(--accent)" }} />
            </div>
            <div>
              <div className="disp" style={{ fontSize: 16, fontWeight: 600 }}>No tickets yet</div>
              <div style={{ fontSize: 12, color: "var(--ink-3)", marginTop: 5, maxWidth: 340, lineHeight: 1.5 }}>
                Capture work to be done, then dispatch an agent straight from a ticket — the board tracks it to&nbsp;done.</div>
            </div>
            <button className="btn primary" onClick={onNew}><Icon name="plus" size="sm" />New ticket</button>
          </div>
        ) : (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 14, padding: 18, alignContent: "start" }}>
            {TICKET_ORDER.map((s) => (
              <Column key={s} status={s} tickets={shown.filter((t) => t.status === s)} agents={agents}
                onOpen={onOpen} onDispatch={onDispatch} onOpenAgent={onOpenAgent} onMove={onMove}
                drag={drag} setDrag={setDrag} onNew={onNew} activeTags={activeTagSel} onToggleTag={toggleTag} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

Object.assign(window, { BacklogView, TicketCard, TICKET_COL, TICKET_ORDER, plainText, TicketChip });

// src/app/backlog/backlog.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  signal,
} from "@angular/core";
import { Ticket, TicketStatus } from "../models";
import { TicketsStore } from "../stores/tickets.store";
import { UiStore } from "../ui/ui.store";
import { ProjectActionsService } from "../projects/project-actions.service";
import { IconComponent } from "../shared/icon.component";
import { TicketCardComponent } from "./ticket-card.component";
import { TagChipComponent } from "./tag-chip.component";
import { TagFilterComponent } from "./tag-filter.component";
import { allTagsOf } from "./tags.util";

type ColDef = { key: TicketStatus; label: string; color: string };

const COLS: ColDef[] = [
  { key: "todo", label: "To do", color: "var(--ink-3)" },
  { key: "inprogress", label: "In progress", color: "var(--st-running)" },
  { key: "done", label: "Done", color: "var(--st-done)" },
];

/**
 * Center-pane backlog board: 3-column kanban for tickets with HTML5 DnD.
 */
@Component({
  selector: "app-backlog",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconComponent, TicketCardComponent, TagChipComponent, TagFilterComponent],
  template: `
    <div style="display:flex;flex-direction:column;min-height:0;background:var(--panel-2)">
      <!-- header -->
      <div style="display:flex;align-items:center;gap:var(--sp-6);padding:var(--sp-6) var(--sp-7);flex:none;border-bottom:1px solid var(--hair);background:var(--panel)">
        <div>
          <h1 class="disp" style="font-size:var(--fs-lg);font-weight:600;letter-spacing:-0.02em">Backlog</h1>
          <span style="font-size:var(--fs-xs);color:var(--ink-3)">
            {{ tickets.all().length }} tickets · {{ openCount() }} open · {{ ui.org }}
          </span>
        </div>
        <div style="margin-left:auto;display:flex;align-items:center;gap:var(--sp-4)">
          <!-- project filter dropdown -->
          <div style="position:relative">
            <button class="btn ghost-hair" style="font-size:var(--fs-sm);color:var(--ink-2)" (click)="filterOpen.set(!filterOpen())">
              <app-icon name="folder" size="sm" color="var(--ink-3)" />
              {{ filterLabel() }}
              <app-icon name="chevronD" size="sm" color="var(--ink-4)" />
            </button>
            @if (filterOpen()) {
              <div
                class="surface"
                style="position:absolute;top:100%;right:0;margin-top:var(--sp-3);z-index:20;padding:var(--sp-2);min-width:190px;box-shadow:var(--shadow)"
                (click)="$event.stopPropagation()"
              >
                @for (p of filterOptions(); track p.id) {
                  <div
                    (click)="setFilter(p.id)"
                    [style.background]="activeFilter() === p.id ? 'var(--panel-3)' : 'transparent'"
                    [style.color]="activeFilter() === p.id ? 'var(--ink)' : 'var(--ink-2)'"
                    style="display:flex;align-items:center;gap:var(--sp-4);padding:var(--sp-3) var(--sp-4);border-radius:var(--r-sm);cursor:pointer;font-size:var(--fs-ui)"
                  >
                    <app-icon [name]="p.icon" size="sm" [color]="p.color" />
                    {{ p.name }}
                  </div>
                }
              </div>
            }
          </div>
          <app-tag-filter
            [allTags]="allTags()"
            [counts]="tagCounts()"
            [selected]="activeTagSel()"
            (selectedChange)="tagSel.set($event)"
          />
          <button class="btn primary" (click)="ui.openTicketDraft()">
            <app-icon name="plus" size="sm" />New ticket
          </button>
        </div>
      </div>

      <!-- active tag-filter summary -->
      @if (activeTagSel().length > 0) {
        <div style="display:flex;align-items:center;gap:var(--sp-4);padding:var(--sp-4) var(--sp-7);flex:none;border-bottom:1px solid var(--hair);background:var(--panel)">
          <span class="up" style="font-size:var(--fs-2xs);color:var(--ink-4);letter-spacing:.1em;flex:none">Filtered by</span>
          <div style="display:flex;flex-wrap:wrap;gap:var(--sp-3)">
            @for (t of activeTagSel(); track t) {
              <app-tag [name]="t" [active]="true" [removable]="true" (remove)="toggleTag($event)" />
            }
          </div>
          <span class="tnum" style="margin-left:auto;flex:none;font-size:var(--fs-xs);color:var(--ink-4)">
            {{ shownTotal() }} of {{ tickets.all().length }}
          </span>
        </div>
      }

      <!-- board body -->
      <div class="scroll-y" style="flex:1" (click)="filterOpen.set(false)">
        @if (isEmpty()) {
          <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;gap:var(--sp-6);min-height:100%;padding:var(--sp-11) var(--sp-8);text-align:center">
            <div style="width:52px;height:52px;border-radius:14px;display:grid;place-items:center;background:var(--ui-sel);border:1px solid var(--ui-sel-2)">
              <app-icon name="layers" size="lg" color="var(--ui-ink)" />
            </div>
            <div>
              <div class="disp" style="font-size:var(--fs-lg);font-weight:600">No tickets yet</div>
              <div style="font-size:var(--fs-ui);color:var(--ink-3);margin-top:var(--sp-2);max-width:340px;line-height:1.5">
                Capture work to be done, then dispatch an agent straight from a ticket — the board tracks it to done.
              </div>
            </div>
            <button class="btn primary" (click)="ui.openTicketDraft()">
              <app-icon name="plus" size="sm" />New ticket
            </button>
          </div>
        } @else {
          <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:var(--sp-6);padding:var(--sp-7);align-content:start">
            @for (col of cols; track col.key) {
              @let colTickets = filtered(col.key);
              @let isTarget = drag() !== null && drag()?.from !== col.key;
              <div
                (dragover)="onDragOver($event, col.key)"
                (dragleave)="onDragLeave()"
                (drop)="onDrop($event, col.key)"
                [style.outline]="over() === col.key && isTarget ? '1.5px dashed color-mix(in oklch,' + col.color + ',transparent 35%)' : '1.5px dashed transparent'"
                [style.outline-offset]="'4px'"
                [style.background]="over() === col.key && isTarget ? 'color-mix(in oklch,' + col.color + ',transparent 94%)' : 'transparent'"
                style="display:flex;flex-direction:column;gap:var(--sp-4);min-width:0;border-radius:var(--r-lg);transition:background .15s"
              >
                <!-- column header -->
                <div
                  [style.border-bottom]="'2px solid ' + col.color"
                  style="display:flex;align-items:center;gap:var(--sp-4);padding:0 var(--sp-1) var(--sp-3);flex:none"
                >
                  <span class="up" style="font-size:var(--fs-xs);color:var(--ink-2)">{{ col.label }}</span>
                  <span class="chip tnum" style="margin-left:auto;font-size:var(--fs-2xs);padding:0 var(--sp-3)">{{ colTickets.length }}</span>
                </div>

                <!-- cards -->
                @for (tk of colTickets; track tk.id) {
                  <app-ticket-card
                    [ticket]="tk"
                    [dragging]="drag()?.id === tk.id"
                    [activeTags]="activeTagSel()"
                    (toggleTag)="toggleTag($event)"
                    (dragStarted)="onCardDragStart($event, tk)"
                    (dragEnd)="onDragEnd()"
                  />
                }

                <!-- todo empty: show "New ticket" button -->
                @if (col.key === 'todo') {
                  <button
                    (click)="ui.openTicketDraft()"
                    style="display:flex;justify-content:center;align-items:center;gap:var(--sp-3);padding:var(--sp-4);border-radius:var(--r-md);border:1px dashed var(--hair-2);color:var(--ink-3);font-size:var(--fs-sm);background:transparent;cursor:pointer"
                  >
                    <app-icon name="plus" size="sm" />New ticket
                  </button>
                } @else if (!colTickets.length) {
                  <div style="padding:var(--sp-6);text-align:center;color:var(--ink-4);font-size:var(--fs-xs);border:1px dashed var(--hair);border-radius:var(--r-md)">empty</div>
                }
              </div>
            }
          </div>
        }
      </div>
    </div>
  `,
})
export class BacklogComponent {
  readonly tickets = inject(TicketsStore);
  readonly ui = inject(UiStore);
  private readonly projects = inject(ProjectActionsService);

  readonly cols = COLS;

  readonly activeFilter = signal<string>("all");
  readonly filterOpen = signal(false);
  readonly tagSel = signal<string[]>([]);
  readonly drag = signal<{ id: string; from: TicketStatus } | null>(null);
  readonly over = signal<TicketStatus | null>(null);

  readonly isEmpty = computed(() => this.tickets.all().length === 0);
  readonly openCount = computed(
    () => this.tickets.all().filter((t) => t.status !== "done").length,
  );

  // ---- tags ----
  readonly allTags = computed(() => allTagsOf(this.tickets.all()));
  readonly tagCounts = computed(() => {
    const counts: Record<string, number> = {};
    for (const t of this.tickets.all()) {
      for (const tg of t.tags ?? []) counts[tg] = (counts[tg] ?? 0) + 1;
    }
    return counts;
  });
  // drop selected tags that no longer exist on any ticket
  readonly activeTagSel = computed(() => {
    const tags = this.allTags();
    return this.tagSel().filter((t) => tags.includes(t));
  });
  // total tickets passing both filters (all statuses) — for the "N of M" summary
  readonly shownTotal = computed(
    () => this.tickets.all().filter((t) => this.passes(t)).length,
  );

  toggleTag(t: string) {
    this.tagSel.update((s) => (s.includes(t) ? s.filter((x) => x !== t) : [...s, t]));
  }

  /** Does a ticket pass the active project + tag filters? Tags use OR semantics. */
  private passes(t: Ticket): boolean {
    const f = this.activeFilter();
    const sel = this.activeTagSel();
    return (
      (f === "all" || t.projectId === f) &&
      (sel.length === 0 || (t.tags ?? []).some((tg) => sel.includes(tg)))
    );
  }

  readonly filterOptions = computed(() => [
    { id: "all", name: "All projects", icon: "layers", color: "var(--ink-3)" },
    ...this.projects.all().map((p) => ({
      id: p.id,
      name: p.name,
      icon: p.icon,
      color: p.color,
    })),
  ]);

  readonly filterLabel = computed(() => {
    const f = this.activeFilter();
    if (f === "all") return "All projects";
    return this.projects.projectOf(f)?.name ?? "All projects";
  });

  filtered(status: TicketStatus): Ticket[] {
    return this.tickets.all().filter((t) => t.status === status && this.passes(t));
  }

  setFilter(id: string) {
    this.activeFilter.set(id);
    this.filterOpen.set(false);
  }

  // ---- drag-and-drop ----
  onCardDragStart(_e: DragEvent, tk: Ticket) {
    this.drag.set({ id: tk.id, from: tk.status });
  }

  onDragOver(e: DragEvent, status: TicketStatus) {
    if (!this.drag()) return;
    e.preventDefault();
    this.over.set(status);
  }

  onDragLeave() {
    this.over.set(null);
  }

  onDrop(e: DragEvent, status: TicketStatus) {
    e.preventDefault();
    const d = this.drag();
    if (d && d.from !== status) {
      void this.tickets.setStatus(d.id, status);
    }
    this.drag.set(null);
    this.over.set(null);
  }

  onDragEnd() {
    this.drag.set(null);
    this.over.set(null);
  }
}
