// design/orrery/project/ticketpage.jsx
/* global React, Icon, StatusDot, ToolBadge, toolMeta, STATUS_META, projectOf, RichEditor, RichView, TICKET_COL, TICKET_ORDER, PROJECTS, TagBar */
// ── TicketPage — dedicated inline page: details + rich notes + comments ──────
const { useState: useStateTP, useEffect: useEffectTP, useRef: useRefTP } = React;

function initials(name) {
  const parts = name.trim().split(/\s+/);
  return ((parts[0] || "")[0] || "?").toUpperCase() + (parts.length > 1 ? (parts[parts.length - 1][0] || "").toUpperCase() : "");
}
const AV_COLORS = ["#a855f7", "#22d3ee", "#34e0a1", "#ff6b35", "#ff4d8d", "#3b82f6", "#f5c451"];
function avColor(name) { let h = 0; for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0; return AV_COLORS[h % AV_COLORS.length]; }

function Avatar({ name, agentTool, size = 28 }) {
  if (agentTool) return <ToolBadge tool={agentTool} size={size} />;
  const c = avColor(name);
  return (
    <span style={{ width: size, height: size, flex: "none", borderRadius: "50%", display: "grid", placeItems: "center",
      fontFamily: "var(--font-disp)", fontSize: size * 0.36, fontWeight: 600, color: c,
      background: "color-mix(in oklch, " + c + ", transparent 84%)", border: "1px solid color-mix(in oklch, " + c + ", transparent 62%)" }}>{initials(name)}</span>
  );
}

// ── one posted comment ───────────────────────────────────────────────────────
function Comment({ c }) {
  const isAgent = c.role === "agent";
  return (
    <div style={{ display: "flex", gap: 11 }}>
      <Avatar name={c.author} agentTool={isAgent ? c.tool : null} size={28} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 5 }}>
          <span className="disp" style={{ fontSize: 12.5, fontWeight: 600, color: "var(--ink)" }}>{c.author}</span>
          {isAgent && <span className="chip" style={{ fontSize: 8.5, padding: "1px 6px", color: "var(--accent-2)", borderColor: "color-mix(in oklch, var(--accent-2), transparent 60%)" }}>AGENT</span>}
          <span style={{ fontSize: 10.5, color: "var(--ink-4)" }} className="tnum">{c.when}</span>
        </div>
        <div style={{ background: isAgent ? "color-mix(in oklch, var(--accent-2), transparent 94%)" : "var(--panel)", border: "1px solid var(--hair)",
          borderRadius: "var(--r-md)", padding: "9px 12px" }}>
          <RichView html={c.body} />
        </div>
      </div>
    </div>
  );
}

// ── side detail row ──────────────────────────────────────────────────────────
function DRow({ label, children }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
      <span className="field-label" style={{ margin: 0 }}>{label}</span>
      {children}
    </div>
  );
}

function StatusSeg({ status, onMove }) {
  return (
    <div style={{ display: "flex", gap: 4, padding: 3, background: "var(--panel-2)", border: "1px solid var(--hair)", borderRadius: "var(--r-md)" }}>
      {TICKET_ORDER.map((s) => {
        const m = TICKET_COL[s], on = status === s;
        return (
          <button key={s} className="btn" onClick={() => onMove(s)}
            style={{ flex: 1, justifyContent: "center", padding: "5px 4px", fontSize: 10.5, borderRadius: "var(--r-sm)", gap: 5,
              background: on ? "color-mix(in oklch, " + m.color + ", transparent 86%)" : "transparent",
              color: on ? m.color : "var(--ink-3)", boxShadow: on ? "0 0 0 1px color-mix(in oklch, " + m.color + ", transparent 60%)" : "none" }}>
            <span className="dot" style={{ background: m.color, animation: "none", width: 6, height: 6 }} />{m.label}
          </button>
        );
      })}
    </div>
  );
}

function TicketPage({ ticket, draft, agents, projects, allTags, onCreate, onUpdate, onDelete, onDispatch, onOpenAgent, onMove, onAddComment, onClose }) {
  const [editing, setEditing] = useStateTP(!!draft);
  const [title, setTitle] = useStateTP(ticket.title || "");
  const [notes, setNotes] = useStateTP(ticket.notes || "");
  const [projectId, setProjectId] = useStateTP(ticket.projectId || "");
  const [tags, setTags] = useStateTP(ticket.tags || []);
  const [comment, setComment] = useStateTP("");
  const [cKey, setCKey] = useStateTP(0);
  const titleRef = useRefTP(null);

  // reset local state when navigating to a different ticket
  useEffectTP(() => {
    setEditing(!!draft); setTitle(ticket.title || ""); setNotes(ticket.notes || "");
    setProjectId(ticket.projectId || ""); setTags(ticket.tags || []); setComment(""); setCKey((k) => k + 1);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ticket.id]);
  useEffectTP(() => { if (editing && draft && titleRef.current) titleRef.current.focus(); }, [editing, draft]);

  const agent = ticket.agentId ? agents.find((a) => a.id === ticket.agentId) : null;
  const m = TICKET_COL[ticket.status];
  const proj = projectOf(ticket.projectId);
  const comments = ticket.comments || [];

  const save = () => {
    const tt = title.trim(); if (!tt) return;
    if (draft) onCreate({ title: tt, notes, projectId: projectId || null, tags });
    else { onUpdate(ticket.id, { title: tt, notes, projectId: projectId || null, tags }); setEditing(false); }
  };
  // tags commit live for existing tickets; staged locally for a draft
  const commitTags = (next) => { setTags(next); if (!draft) onUpdate(ticket.id, { tags: next }); };
  const cancel = () => {
    if (draft) { onClose && onClose(); return; }
    setTitle(ticket.title || ""); setNotes(ticket.notes || ""); setProjectId(ticket.projectId || ""); setEditing(false);
  };
  const post = () => { const b = comment.trim(); if (!b) return; onAddComment(ticket.id, { body: comment }); setComment(""); setCKey((k) => k + 1); };

  return (
    <div style={{ display: "flex", flexDirection: "column", minHeight: 0, background: "var(--panel-2)" }}>
      {/* header */}
      <div style={{ padding: "12px 22px", borderBottom: "1px solid var(--hair)", background: "var(--panel)", flex: "none" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 9, fontSize: 11, color: "var(--ink-3)", marginBottom: 9 }}>
          <Icon name="layers" size="sm" style={{ color: "var(--accent)" }} />
          <span>Backlog</span>
          <Icon name="chevron" size="sm" style={{ width: 11, height: 11, color: "var(--ink-4)" }} />
          <span className="tnum">{draft ? "New ticket" : "#" + ticket.id.replace(/^t/, "")}</span>
          <span style={{ marginLeft: "auto", display: "flex", gap: 6 }} className="up">
            <span style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 9.5, padding: "3px 9px", borderRadius: 999, letterSpacing: ".1em",
              color: m.color, border: "1px solid color-mix(in oklch, " + m.color + ", transparent 62%)", background: "color-mix(in oklch, " + m.color + ", transparent 88%)" }}>
              <span className="dot" style={{ background: m.color, animation: "none" }} />{m.label}</span>
          </span>
        </div>

        {editing
          ? <input ref={titleRef} value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Ticket title — what needs to be done?"
              onKeyDown={(e) => { if (e.key === "Enter") save(); }}
              style={{ width: "100%", background: "transparent", border: "none", outline: "none", color: "var(--ink)",
                fontFamily: "var(--font-disp)", fontSize: 22, fontWeight: 600, letterSpacing: "-0.02em", padding: 0 }} />
          : <h1 className="disp" style={{ fontSize: 22, fontWeight: 600, letterSpacing: "-0.02em", lineHeight: 1.25, textWrap: "balance" }}>{ticket.title}</h1>}

        <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 12 }}>
          {editing ? (
            <React.Fragment>
              <button className="btn primary" disabled={!title.trim()} onClick={save}><Icon name={draft ? "plus" : "check"} size="sm" />{draft ? "Create ticket" : "Save"}</button>
              <button className="btn ghost-hair" onClick={cancel}>Cancel</button>
            </React.Fragment>
          ) : (
            <React.Fragment>
              {ticket.status === "todo" && <button className="btn primary" onClick={() => onDispatch(ticket)}><Icon name="bolt" size="sm" />Dispatch agent</button>}
              {agent && <button className="btn ghost-hair" onClick={() => onOpenAgent(agent.id)}><Icon name="enter" size="sm" />Open agent</button>}
              <button className="btn ghost-hair" onClick={() => setEditing(true)}><Icon name="rename" size="sm" />Edit</button>
              <button className="btn ghost-hair" onClick={() => onDelete(ticket.id)} style={{ color: "var(--ink-3)" }}
                onMouseEnter={(e) => e.currentTarget.style.color = "var(--st-blocked)"} onMouseLeave={(e) => e.currentTarget.style.color = "var(--ink-3)"}>
                <Icon name="trash" size="sm" />Delete</button>
            </React.Fragment>
          )}
        </div>
      </div>

      {/* body */}
      <div className="scroll-y" style={{ flex: 1 }}>
        <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 268px", gap: 28, padding: "22px 24px", maxWidth: 1040, margin: "0 auto", alignItems: "start" }}>
          {/* main */}
          <div style={{ display: "flex", flexDirection: "column", gap: 24, minWidth: 0 }}>
            <div>
              <div className="up" style={{ fontSize: 10, color: "var(--ink-3)", marginBottom: 9 }}>What should be done</div>
              {editing
                ? <RichEditor value={notes} onChange={setNotes} minHeight={150} placeholder="Describe the work — context, acceptance criteria, links…" />
                : (plainTextNonEmpty(ticket.notes)
                    ? <RichView html={ticket.notes} style={{ fontSize: 12.5 }} />
                    : <div style={{ fontSize: 12, color: "var(--ink-4)", fontStyle: "italic" }}>No description yet.</div>)}
            </div>

            {/* comments */}
            {!draft && (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                <div className="up" style={{ fontSize: 10, color: "var(--ink-3)", display: "flex", alignItems: "center", gap: 7 }}>
                  <Icon name="chat" size="sm" />Comments<span className="chip tnum" style={{ fontSize: 9, padding: "0 6px" }}>{comments.length}</span>
                </div>
                {comments.map((c) => <Comment key={c.id} c={c} />)}
                {!comments.length && <div style={{ fontSize: 11.5, color: "var(--ink-4)" }}>No comments yet — start the thread.</div>}

                {/* composer */}
                <div style={{ display: "flex", gap: 11, marginTop: 2 }}>
                  <Avatar name="You" size={28} />
                  <div style={{ flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 8 }}>
                    <RichEditor value="" onChange={setComment} minHeight={70} compact resetSignal={cKey} placeholder="Leave a comment…  ⌘B bold · ⌘K link" />
                    <div style={{ display: "flex", justifyContent: "flex-end" }}>
                      <button className="btn primary" disabled={!comment.trim()} onClick={post}><Icon name="chat" size="sm" />Comment</button>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* side details */}
          <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
            <DRow label="Status">
              <StatusSeg status={ticket.status} onMove={(s) => onMove(ticket.id, s)} />
            </DRow>
            <DRow label="Project">
              {editing
                ? <select className="osel" value={projectId} onChange={(e) => setProjectId(e.target.value)}>
                    <option value="">No project</option>
                    {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
                  </select>
                : (proj
                    ? <span style={{ display: "inline-flex", alignItems: "center", gap: 7, fontSize: 12, color: proj.color }}>
                        <span style={{ width: 19, height: 19, borderRadius: 5, display: "grid", placeItems: "center", flex: "none",
                          background: "color-mix(in oklch, " + proj.color + ", transparent 82%)", border: "1px solid color-mix(in oklch, " + proj.color + ", transparent 62%)" }}>
                          <Icon name={proj.icon} size="sm" style={{ width: 12, height: 12, color: proj.color }} /></span>{proj.name}</span>
                    : <span style={{ fontSize: 12, color: "var(--ink-4)" }}>No project</span>)}
            </DRow>

            <DRow label="Tags">
              <TagBar allTags={allTags || []} tags={tags} onChange={commitTags} />
            </DRow>

            <DRow label="Agent">
              {agent ? (
                <div onClick={() => onOpenAgent(agent.id)} style={{ display: "flex", alignItems: "center", gap: 9, padding: "9px 10px", borderRadius: "var(--r-md)",
                  background: "var(--panel)", border: "1px solid var(--hair)", cursor: "pointer" }}
                  onMouseEnter={(e) => e.currentTarget.style.borderColor = "var(--hair-2)"} onMouseLeave={(e) => e.currentTarget.style.borderColor = "var(--hair)"}>
                  <ToolBadge tool={agent.tool} size={20} />
                  <div style={{ minWidth: 0, flex: 1 }}>
                    <div className="disp" style={{ fontSize: 12, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{agent.name}</div>
                    <div style={{ display: "flex", alignItems: "center", gap: 5, fontSize: 10, color: (STATUS_META[agent.status] || {}).color, marginTop: 2 }}>
                      <StatusDot status={agent.status} />{(STATUS_META[agent.status] || {}).label}</div>
                  </div>
                  <Icon name="enter" size="sm" style={{ color: "var(--ink-4)", flex: "none" }} />
                </div>
              ) : ticket.status === "todo" ? (
                <button className="btn ghost-hair" onClick={() => onDispatch(ticket)} style={{ justifyContent: "center", color: "var(--accent)", borderColor: "color-mix(in oklch, var(--accent), transparent 55%)" }}>
                  <Icon name="bolt" size="sm" />Dispatch an agent</button>
              ) : <span style={{ fontSize: 12, color: "var(--ink-4)" }}>None attached</span>}
            </DRow>

            {agent && (
              <DRow label="Branch">
                <span style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5, color: "var(--ink-2)" }}>
                  <Icon name="branch" size="sm" style={{ width: 12, height: 12, color: "var(--accent-2)" }} />{agent.branch}</span>
              </DRow>
            )}

            <DRow label="Created">
              <span style={{ fontSize: 11.5, color: "var(--ink-2)" }} className="tnum">{draft ? "just now" : (ticket.created || "—")}</span>
            </DRow>
          </div>
        </div>
      </div>
    </div>
  );
}

function plainTextNonEmpty(html) { if (!html) return false; const d = document.createElement("div"); d.innerHTML = html; return (d.textContent || "").trim().length > 0; }

Object.assign(window, { TicketPage });

// src/app/backlog/ticket-page.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from "@angular/core";
import { Comment, TicketStatus } from "../models";
import { TicketsStore } from "../stores/tickets.store";
import { UiStore } from "../ui/ui.store";
import { AgentRuntimeService } from "../agents/agent-runtime.service";
import { ProjectActionsService } from "../projects/project-actions.service";
import { IconComponent } from "../shared/icon.component";
import { RichEditorComponent } from "../shared/rich-editor/rich-editor.component";
import { RichViewComponent } from "../shared/rich-editor/rich-view.component";
import { ToolBadgeComponent } from "../shared/tool-badge.component";
import { StatusDotComponent } from "../shared/status-dot.component";
import { STATUS_META } from "../utils";

// ── Status token map (mirrors design TICKET_COL) ─────────────────────────────
export interface TicketStatusMeta {
  label: string;
  color: string;
}
export const TICKET_STATUS: Record<TicketStatus, TicketStatusMeta> = {
  todo: { label: "To do", color: "var(--ink-3)" },
  inprogress: { label: "In progress", color: "var(--accent)" },
  done: { label: "Done", color: "var(--st-done)" },
};
export const TICKET_STATUS_ORDER: TicketStatus[] = ["todo", "inprogress", "done"];

// ── Avatar helpers ────────────────────────────────────────────────────────────
const AV_COLORS = [
  "#a855f7",
  "#22d3ee",
  "#34e0a1",
  "#ff6b35",
  "#ff4d8d",
  "#3b82f6",
  "#f5c451",
];
export function avColor(name: string): string {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = ((h * 31 + name.charCodeAt(i)) >>> 0);
  return AV_COLORS[h % AV_COLORS.length];
}
export function initials(name: string): string {
  const parts = name.trim().split(/\s+/);
  return (
    ((parts[0] || "")[0] || "?").toUpperCase() +
    (parts.length > 1 ? (parts[parts.length - 1][0] || "").toUpperCase() : "")
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────────
export function plainTextNonEmpty(html: string | null | undefined): boolean {
  if (!html) return false;
  return html.replace(/<[^>]*>/g, "").trim().length > 0;
}

export function shortId(id: string): string {
  return id.replace(/^t/, "");
}

export function relativeTime(ts: number): string {
  const diff = Math.floor((Date.now() - ts) / 1000);
  if (diff < 60) return "just now";
  if (diff < 3600) return Math.floor(diff / 60) + "m ago";
  if (diff < 86400) return Math.floor(diff / 3600) + "h ago";
  return Math.floor(diff / 86400) + "d ago";
}

export function fmtCreated(ts: number): string {
  return new Date(ts).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

// ── Comment row component ─────────────────────────────────────────────────────
@Component({
  selector: "app-ticket-comment",
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [RichViewComponent, ToolBadgeComponent],
  template: `
    @let c = comment();
    @let isAgent = c.role === 'agent';
    <div style="display:flex;gap:11px">
      <!-- avatar / tool badge -->
      @if (isAgent && c.tool) {
        <div style="flex:none;width:28px;height:28px;display:grid;place-items:center">
          <app-tool-badge [tool]="$any(c.tool)" [size]="28" />
        </div>
      } @else {
        <span
          [style.width.px]="28"
          [style.height.px]="28"
          [style.color]="avatarColor()"
          [style.background]="avatarBg()"
          [style.border]="avatarBorder()"
          style="flex:none;border-radius:50%;display:grid;place-items:center;font-family:var(--font-disp);font-size:10px;font-weight:600"
        >{{ avatarInitials() }}</span>
      }
      <div style="flex:1;min-width:0">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
          <span class="disp" style="font-size:12.5px;font-weight:600;color:var(--ink)">{{ c.author }}</span>
          @if (isAgent) {
            <span class="chip up" style="font-size:8.5px;padding:1px 6px;color:var(--accent-2);border-color:color-mix(in oklch,var(--accent-2),transparent 60%)">AGENT</span>
          }
          <span class="tnum" style="font-size:10.5px;color:var(--ink-4)">{{ when() }}</span>
        </div>
        <div
          [style.background]="isAgent ? 'color-mix(in oklch,var(--accent-2),transparent 94%)' : 'var(--panel)'"
          style="border:1px solid var(--hair);border-radius:var(--r-md);padding:9px 12px"
        >
          <app-rich-view [html]="c.body" [compact]="true" />
        </div>
      </div>
    </div>
  `,
})
export class TicketCommentComponent {
  readonly comment = input.required<Comment>();

  readonly avatarColor = computed(() => avColor(this.comment().author));
  readonly avatarBg = computed(() => {
    const c = avColor(this.comment().author);
    return `color-mix(in oklch,${c},transparent 84%)`;
  });
  readonly avatarBorder = computed(() => {
    const c = avColor(this.comment().author);
    return `1px solid color-mix(in oklch,${c},transparent 62%)`;
  });
  readonly avatarInitials = computed(() => initials(this.comment().author));
  readonly when = computed(() => relativeTime(this.comment().createdAt));
}

// ── Ticket Page ───────────────────────────────────────────────────────────────
@Component({
  selector: "app-ticket-page",
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [
    IconComponent,
    RichEditorComponent,
    RichViewComponent,
    ToolBadgeComponent,
    StatusDotComponent,
    TicketCommentComponent,
  ],
  template: `
    @let tk = ticket();
    @let isDraft = ticketId() === 'draft';
    @let isEditing = editing();
    @let ag = resolvedAgent();
    @let sm = statusMeta();

    <div style="display:flex;flex-direction:column;min-height:0;height:100%;background:var(--panel-2)">

      <!-- ── Header ── -->
      <div style="padding:12px 22px;border-bottom:1px solid var(--hair);background:var(--panel);flex:none">

        <!-- breadcrumb + status pill -->
        <div style="display:flex;align-items:center;gap:9px;font-size:11px;color:var(--ink-3);margin-bottom:9px">
          <app-icon name="layers" size="sm" [color]="'var(--accent)'" />
          <span>Backlog</span>
          <app-icon name="chevron" size="sm" style="width:11px;height:11px" [color]="'var(--ink-4)'" />
          <span class="tnum">{{ isDraft ? 'New ticket' : '#' + (tk ? shortId(tk.id) : '') }}</span>
          <span style="margin-left:auto">
            <span
              class="up"
              [style.color]="sm.color"
              [style.border]="'1px solid color-mix(in oklch,' + sm.color + ',transparent 62%)'"
              [style.background]="'color-mix(in oklch,' + sm.color + ',transparent 88%)'"
              style="display:inline-flex;align-items:center;gap:6px;font-size:9.5px;padding:3px 9px;border-radius:999px;letter-spacing:0.1em"
            >
              <span class="dot" [style.background]="sm.color" style="animation:none"></span>
              {{ sm.label }}
            </span>
          </span>
        </div>

        <!-- title -->
        @if (isEditing) {
          <input
            #titleInput
            [value]="draftTitle()"
            (input)="draftTitle.set($any($event.target).value)"
            (keydown.enter)="save()"
            placeholder="Ticket title — what needs to be done?"
            style="width:100%;background:transparent;border:none;outline:none;color:var(--ink);font-family:var(--font-disp);font-size:22px;font-weight:600;letter-spacing:-0.02em;padding:0"
          />
        } @else if (tk) {
          <h1 class="disp" style="font-size:22px;font-weight:600;letter-spacing:-0.02em;line-height:1.25;text-wrap:balance">
            {{ tk.title }}
          </h1>
        }

        <!-- actions row -->
        <div style="display:flex;align-items:center;gap:8px;margin-top:12px">
          @if (isEditing) {
            <button class="btn primary" [disabled]="!draftTitle().trim()" (click)="save()">
              <app-icon [name]="isDraft ? 'plus' : 'check'" size="sm" />
              {{ isDraft ? 'Create ticket' : 'Save' }}
            </button>
            <button class="btn ghost-hair" (click)="cancel()">Cancel</button>
          } @else if (tk) {
            @if (tk.status === 'todo') {
              <button class="btn primary" (click)="dispatch()">
                <app-icon name="bolt" size="sm" />Dispatch agent
              </button>
            }
            @if (ag) {
              <button class="btn ghost-hair" (click)="openAgent()">
                <app-icon name="enter" size="sm" />Open agent
              </button>
            }
            <button class="btn ghost-hair" (click)="editing.set(true)">
              <app-icon name="rename" size="sm" />Edit
            </button>
            <button
              class="btn ghost-hair"
              (click)="deleteTicket()"
              [style.color]="deleteHovered() ? 'var(--st-blocked)' : 'var(--ink-3)'"
              (mouseenter)="deleteHovered.set(true)"
              (mouseleave)="deleteHovered.set(false)"
            >
              <app-icon name="trash" size="sm" />Delete
            </button>
          }
        </div>
      </div>

      <!-- ── Body ── -->
      <div class="scroll-y" style="flex:1">
        <div style="display:grid;grid-template-columns:minmax(0,1fr) 268px;gap:28px;padding:22px 24px;max-width:1040px;margin:0 auto;align-items:start">

          <!-- ── MAIN COLUMN ── -->
          <div style="display:flex;flex-direction:column;gap:24px;min-width:0">

            <!-- Notes -->
            <div>
              <div class="up" style="font-size:10px;color:var(--ink-3);margin-bottom:9px">What should be done</div>
              @if (isEditing) {
                <app-rich-editor
                  [value]="draftNotes()"
                  (valueChange)="draftNotes.set($event)"
                  [minHeight]="150"
                  placeholder="Describe the work — context, acceptance criteria, links…"
                />
              } @else if (tk) {
                @if (plainTextNonEmpty(tk.notes)) {
                  <app-rich-view [html]="tk.notes" />
                } @else {
                  <div style="font-size:12px;color:var(--ink-4);font-style:italic">No description yet.</div>
                }
              }
            </div>

            <!-- Comments (not in draft mode) -->
            @if (!isDraft) {
              <div style="display:flex;flex-direction:column;gap:14px">
                <!-- section header -->
                <div class="up" style="font-size:10px;color:var(--ink-3);display:flex;align-items:center;gap:7px">
                  <app-icon name="chat" size="sm" />
                  Comments
                  <span class="chip tnum" style="font-size:9px;padding:0 6px">{{ comments().length }}</span>
                </div>

                @if (comments().length === 0) {
                  <div style="font-size:11.5px;color:var(--ink-4)">No comments yet — start the thread.</div>
                } @else {
                  @for (c of comments(); track c.id) {
                    <app-ticket-comment [comment]="c" />
                  }
                }

                <!-- composer -->
                <div style="display:flex;gap:11px;margin-top:2px">
                  <!-- "You" avatar -->
                  <span
                    style="flex:none;width:28px;height:28px;border-radius:50%;display:grid;place-items:center;font-family:var(--font-disp);font-size:10px;font-weight:600"
                    [style.color]="youAvatarColor"
                    [style.background]="youAvatarBg"
                    [style.border]="youAvatarBorder"
                  >Y</span>
                  <div style="flex:1;min-width:0;display:flex;flex-direction:column;gap:8px">
                    <app-rich-editor
                      [value]="''"
                      (valueChange)="composerBody.set($event)"
                      [minHeight]="70"
                      [compact]="true"
                      [resetSignal]="composerResetSignal()"
                      placeholder="Leave a comment…  ⌘B bold · ⌘K link"
                    />
                    <div style="display:flex;justify-content:flex-end">
                      <button
                        class="btn primary"
                        [disabled]="!composerHasContent()"
                        (click)="postComment()"
                      >
                        <app-icon name="chat" size="sm" />Comment
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            }
          </div>

          <!-- ── SIDE RAIL ── -->
          <div style="display:flex;flex-direction:column;gap:18px">

            <!-- Status segmented control -->
            <div style="display:flex;flex-direction:column;gap:6px">
              <span class="field-label" style="margin:0">Status</span>
              <div style="display:flex;gap:4px;padding:3px;background:var(--panel-2);border:1px solid var(--hair);border-radius:var(--r-md)">
                @for (s of statusOrder; track s) {
                  @let sm2 = ticketStatusMeta(s);
                  @let on = (isDraft ? 'todo' : (tk?.status ?? 'todo')) === s;
                  <button
                    class="btn"
                    (click)="moveStatus(s)"
                    [style.flex]="1"
                    style="justify-content:center;padding:5px 4px;font-size:10.5px;border-radius:var(--r-sm);gap:5px"
                    [style.background]="on ? 'color-mix(in oklch,' + sm2.color + ',transparent 86%)' : 'transparent'"
                    [style.color]="on ? sm2.color : 'var(--ink-3)'"
                    [style.box-shadow]="on ? '0 0 0 1px color-mix(in oklch,' + sm2.color + ',transparent 60%)' : 'none'"
                  >
                    <span class="dot" [style.background]="sm2.color" style="animation:none;width:6px;height:6px"></span>
                    {{ sm2.label }}
                  </button>
                }
              </div>
            </div>

            <!-- Project -->
            <div style="display:flex;flex-direction:column;gap:6px">
              <span class="field-label" style="margin:0">Project</span>
              @if (isEditing) {
                <select class="osel" [value]="draftProjectId()" (change)="draftProjectId.set($any($event.target).value)">
                  <option value="">No project</option>
                  @for (p of projects.all(); track p.id) {
                    <option [value]="p.id">{{ p.name }}</option>
                  }
                </select>
              } @else {
                @let proj = resolvedProject();
                @if (proj) {
                  <span style="display:inline-flex;align-items:center;gap:7px;font-size:12px" [style.color]="proj.color">
                    <span
                      style="width:19px;height:19px;border-radius:5px;display:grid;place-items:center;flex:none"
                      [style.background]="'color-mix(in oklch,' + proj.color + ',transparent 82%)'"
                      [style.border]="'1px solid color-mix(in oklch,' + proj.color + ',transparent 62%)'"
                    >
                      <app-icon [name]="proj.icon" size="sm" [color]="proj.color" style="width:12px;height:12px" />
                    </span>
                    {{ proj.name }}
                  </span>
                } @else {
                  <span style="font-size:12px;color:var(--ink-4)">No project</span>
                }
              }
            </div>

            <!-- Agent -->
            <div style="display:flex;flex-direction:column;gap:6px">
              <span class="field-label" style="margin:0">Agent</span>
              @if (ag && tk) {
                <div
                  (click)="openAgent()"
                  (mouseenter)="agentHovered.set(true)"
                  (mouseleave)="agentHovered.set(false)"
                  style="display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:var(--r-md);background:var(--panel);cursor:pointer;transition:border-color .15s"
                  [style.border]="agentHovered() ? '1px solid var(--hair-2)' : '1px solid var(--hair)'"
                >
                  <app-tool-badge [tool]="ag.tool" [size]="20" />
                  <div style="min-width:0;flex:1">
                    <div class="disp" style="font-size:12px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ ag.name }}</div>
                    <div style="display:flex;align-items:center;gap:5px;font-size:10px;margin-top:2px" [style.color]="agentMeta().color">
                      <app-status-dot [status]="ag.status" />{{ agentMeta().label }}
                    </div>
                  </div>
                  <app-icon name="enter" size="sm" [color]="'var(--ink-4)'" style="flex:none" />
                </div>
              } @else if (tk?.status === 'todo') {
                <button
                  class="btn ghost-hair"
                  (click)="dispatch()"
                  style="justify-content:center;color:var(--accent);border-color:color-mix(in oklch,var(--accent),transparent 55%)"
                >
                  <app-icon name="bolt" size="sm" />Dispatch an agent
                </button>
              } @else {
                <span style="font-size:12px;color:var(--ink-4)">None attached</span>
              }
            </div>

            <!-- Branch (only when agent exists) -->
            @if (ag) {
              <div style="display:flex;flex-direction:column;gap:6px">
                <span class="field-label" style="margin:0">Branch</span>
                <span style="display:inline-flex;align-items:center;gap:6px;font-size:11.5px;color:var(--ink-2)">
                  <app-icon name="branch" size="sm" style="width:12px;height:12px" [color]="'var(--accent-2)'" />
                  {{ ag.branch.replace('agent/', '') }}
                </span>
              </div>
            }

            <!-- Created -->
            <div style="display:flex;flex-direction:column;gap:6px">
              <span class="field-label" style="margin:0">Created</span>
              <span class="tnum" style="font-size:11.5px;color:var(--ink-2)">
                {{ isDraft ? 'just now' : (tk ? fmtCreated(tk.createdAt) : '—') }}
              </span>
            </div>

          </div>
        </div>
      </div>
    </div>
  `,
})
export class TicketPageComponent {
  readonly ticketId = input.required<string>();

  readonly ticketsStore = inject(TicketsStore);
  readonly ui = inject(UiStore);
  private readonly runtime = inject(AgentRuntimeService);
  readonly projects = inject(ProjectActionsService);

  // ── editing state ─────────────────────────────────────────────────────────
  readonly editing = signal(false);
  readonly draftTitle = signal("");
  readonly draftNotes = signal("");
  readonly draftProjectId = signal("");
  readonly deleteHovered = signal(false);
  readonly agentHovered = signal(false);

  // ── comments state ────────────────────────────────────────────────────────
  readonly comments = signal<Comment[]>([]);
  readonly composerBody = signal("");
  readonly composerResetSignal = signal(0);

  readonly composerHasContent = computed(() =>
    this.composerBody().replace(/<[^>]*>/g, "").trim().length > 0,
  );

  // ── derived ticket ────────────────────────────────────────────────────────
  readonly ticket = computed(() => {
    const id = this.ticketId();
    if (id === "draft") return null;
    return this.ticketsStore.byId(id) ?? null;
  });

  readonly resolvedAgent = computed(() => {
    const tk = this.ticket();
    if (!tk?.agentId) return null;
    return this.runtime.agents().find((a) => a.id === tk.agentId) ?? null;
  });

  readonly resolvedProject = computed(() => {
    // in edit mode use the draft project id
    const id = this.editing() ? this.draftProjectId() : (this.ticket()?.projectId ?? "");
    return id ? this.projects.projectOf(id) : undefined;
  });

  readonly statusMeta = computed((): TicketStatusMeta => {
    const id = this.ticketId();
    if (id === "draft") return TICKET_STATUS["todo"];
    const tk = this.ticket();
    return tk ? TICKET_STATUS[tk.status] : TICKET_STATUS["todo"];
  });

  readonly agentMeta = computed(() => {
    const ag = this.resolvedAgent();
    if (!ag) return STATUS_META["idle"];
    return STATUS_META[ag.status] ?? STATUS_META["idle"];
  });

  // ── static helpers (template-accessible) ─────────────────────────────────
  readonly statusOrder = TICKET_STATUS_ORDER;
  readonly plainTextNonEmpty = plainTextNonEmpty;
  readonly shortId = shortId;
  readonly fmtCreated = fmtCreated;

  ticketStatusMeta(s: TicketStatus): TicketStatusMeta {
    return TICKET_STATUS[s];
  }

  // "You" avatar vars (constant, so compute once)
  readonly youAvatarColor = avColor("You");
  readonly youAvatarBg = `color-mix(in oklch,${avColor("You")},transparent 84%)`;
  readonly youAvatarBorder = `1px solid color-mix(in oklch,${avColor("You")},transparent 62%)`;

  constructor() {
    // When ticketId changes: reset edit state + reload comments
    effect(() => {
      const id = this.ticketId();
      const isDraft = id === "draft";
      const tk = isDraft ? null : this.ticketsStore.byId(id);

      this.editing.set(isDraft);
      this.draftTitle.set(tk?.title ?? "");
      this.draftNotes.set(tk?.notes ?? "");
      this.draftProjectId.set(tk?.projectId ?? "");
      this.deleteHovered.set(false);
      this.composerBody.set("");

      if (!isDraft) {
        void this.loadComments(id);
      } else {
        this.comments.set([]);
      }
    });
  }

  private async loadComments(ticketId: string): Promise<void> {
    try {
      const list = await this.ticketsStore.comments(ticketId);
      this.comments.set(list);
    } catch {
      this.comments.set([]);
    }
  }

  // ── actions ───────────────────────────────────────────────────────────────

  async save(): Promise<void> {
    const title = this.draftTitle().trim();
    if (!title) return;
    const isDraft = this.ticketId() === "draft";

    if (isDraft) {
      try {
        const created = await this.ticketsStore.create({
          title,
          notes: this.draftNotes() || undefined,
          projectId: this.draftProjectId() || null,
        });
        // Close the draft tab and open the new ticket
        const draftTab = this.ui.tabs().find(
          (t) => t.kind === "ticket" && t.ticketId === "draft",
        );
        if (draftTab) this.ui.closeTab(draftTab.id);
        this.ui.openTicket(created.id);
      } catch {
        /* backend unavailable */
      }
    } else {
      const id = this.ticketId();
      try {
        await this.ticketsStore.update(id, {
          title,
          notes: this.draftNotes() || undefined,
          projectId: this.draftProjectId() || null,
        });
      } catch {
        /* ignore */
      }
      this.editing.set(false);
    }
  }

  cancel(): void {
    const isDraft = this.ticketId() === "draft";
    if (isDraft) {
      const draftTab = this.ui.tabs().find(
        (t) => t.kind === "ticket" && t.ticketId === "draft",
      );
      if (draftTab) this.ui.closeTab(draftTab.id);
      return;
    }
    const tk = this.ticket();
    this.draftTitle.set(tk?.title ?? "");
    this.draftNotes.set(tk?.notes ?? "");
    this.draftProjectId.set(tk?.projectId ?? "");
    this.editing.set(false);
  }

  async deleteTicket(): Promise<void> {
    const id = this.ticketId();
    if (id === "draft") return;
    const tab = this.ui.tabs().find((t) => t.kind === "ticket" && t.ticketId === id);
    try {
      await this.ticketsStore.remove(id);
    } catch {
      /* ignore */
    }
    if (tab) this.ui.closeTab(tab.id);
  }

  dispatch(): void {
    const tk = this.ticket();
    if (!tk) return;
    this.ui.dispatchTicket({ id: tk.id, projectId: tk.projectId });
  }

  openAgent(): void {
    const ag = this.resolvedAgent();
    if (ag) this.ui.openAgent(ag.id);
  }

  moveStatus(s: TicketStatus): void {
    const id = this.ticketId();
    if (id === "draft") return;
    void this.ticketsStore.setStatus(id, s);
  }

  async postComment(): Promise<void> {
    const body = this.composerBody();
    if (!body.replace(/<[^>]*>/g, "").trim()) return;
    const id = this.ticketId();
    if (id === "draft") return;
    try {
      await this.ticketsStore.addComment(id, { body });
      await this.loadComments(id);
      this.composerResetSignal.update((n) => n + 1);
      this.composerBody.set("");
    } catch {
      /* ignore */
    }
  }
}
