// design/orrery/project/toolwindow.jsx
/* global React, Icon */
// Orrery — bottom tool window (IntelliJ-style dock). Panels register themselves
// into window.TOOL_PANELS; the shell owns the tab strip, resize and close.

const { useState: useStateTW, useRef: useRefTW, useEffect: useEffectTW } = React;

window.TOOL_PANELS = window.TOOL_PANELS || {};
// order of the tab strip
window.TOOL_ORDER = ["search", "graph", "branches", "history", "cost", "github"];

function ToolWindow({ tool, onSelect, onClose, ctx }) {
  const [h, setH] = useStateTW(() => Math.round(Math.min(420, Math.max(240, window.innerHeight * 0.36))));
  // a tab can hold agents from several projects, so the tool window carries its
  // own scope: pick the project (and optionally one worktree) the panels act on
  const projects = ctx.projects || [];
  const [scope, setScope] = useStateTW(() => ({ projectId: (ctx.scopeAgent && ctx.scopeAgent.projectId) || (projects[0] || {}).id, agentId: (ctx.scopeAgent || {}).id || null }));
  const project = projects.find((p) => p.id === scope.projectId) || projects[0] || null;
  const projAgents = (ctx.agents || []).filter((a) => project && a.projectId === project.id);
  const agent = projAgents.find((a) => a.id === scope.agentId) || projAgents[0] || null;
  const focus = ctx.scopeAgent;
  const outOfSync = !!(focus && (focus.projectId !== (project && project.id) || focus.id !== (agent && agent.id)) && projects.some((p) => p.id === focus.projectId));
  const scoped = Object.assign({}, ctx, { project, projectId: project && project.id, agents: projAgents, allAgents: ctx.agents, scopeAgent: agent });
  const drag = useRefTW(null);
  useEffectTW(() => {
    const move = (e) => { if (!drag.current) return; const dy = drag.current.y - e.clientY; setH(Math.max(160, Math.min(window.innerHeight - 200, drag.current.h + dy))); };
    const up = () => { drag.current = null; document.body.style.cursor = ""; };
    window.addEventListener("mousemove", move); window.addEventListener("mouseup", up);
    return () => { window.removeEventListener("mousemove", move); window.removeEventListener("mouseup", up); };
  }, []);
  const panels = window.TOOL_ORDER.map((k) => window.TOOL_PANELS[k]).filter(Boolean);
  const panel = window.TOOL_PANELS[tool.kind];
  const Body = panel && panel.Component;
  return (
    <div style={{ height: h, flex: "none", display: "flex", flexDirection: "column", minHeight: 0, background: "var(--panel)", borderTop: "1px solid var(--hair)" }}>
      <div onMouseDown={(e) => { drag.current = { y: e.clientY, h }; document.body.style.cursor = "row-resize"; }}
        style={{ height: 4, marginTop: -3, cursor: "row-resize", flex: "none" }} />
      <div style={{ display: "flex", alignItems: "stretch", gap: 2, padding: "0 8px", borderBottom: "1px solid var(--hair)", flex: "none", background: "var(--panel-2)" }}>
        {panels.map((p) => {
          const on = p.kind === tool.kind;
          return (
            <button key={p.kind} className="btn" onClick={() => onSelect({ kind: p.kind })}
              style={{ padding: "7px 10px", borderRadius: 0, position: "relative", fontSize: 11.5, color: on ? "var(--ink)" : "var(--ink-3)" }}>
              {on && <span style={{ position: "absolute", left: 8, right: 8, bottom: 0, height: 2, background: "linear-gradient(90deg, var(--accent), var(--accent-2))" }} />}
              <Icon name={p.icon} size="sm" style={{ color: on ? "var(--accent)" : "inherit" }} />{p.label}
            </button>
          );
        })}
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 6, paddingLeft: 10 }}>
          <span className="up" style={{ fontSize: 8.5, color: "var(--ink-4)", flex: "none" }}>scope</span>
          {project && (
            <span style={{ display: "flex", alignItems: "center", gap: 5, flex: "none" }}>
              <Icon name={project.icon} size="sm" style={{ width: 12, height: 12, color: project.color }} />
              <select className="osel" value={project.id} onChange={(e) => setScope({ projectId: e.target.value, agentId: null })}
                style={{ width: 152, padding: "3px 22px 3px 8px", fontSize: 10.5 }}>
                {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </span>
          )}
          <select className="osel" value={(agent && agent.id) || ""} onChange={(e) => setScope((s) => ({ ...s, agentId: e.target.value || null }))}
            title="Worktree the panel reads from" style={{ width: 150, padding: "3px 22px 3px 8px", fontSize: 10.5, flex: "none" }}>
            {!projAgents.length && <option value="">no worktrees</option>}
            {projAgents.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
          </select>
          {outOfSync && (
            <button className="btn ghost-hair" title={"Follow the focused agent · " + focus.name} style={{ padding: "2px 7px", fontSize: 10, color: "var(--accent-2)", flex: "none" }}
              onClick={() => setScope({ projectId: focus.projectId, agentId: focus.id })}>
              <Icon name="link" size="sm" style={{ width: 11, height: 11 }} />{focus.name}
            </button>
          )}
          <button className="pane-btn" onClick={onClose} title="Hide tool window" style={{ alignSelf: "center" }}>
            <Icon name="x" size="sm" />
          </button>
        </div>
      </div>
      <div style={{ flex: 1, minHeight: 0, display: "flex", flexDirection: "column", background: "var(--panel)" }}>
        {Body ? <Body key={(project && project.id) + ":" + ((agent && agent.id) || "none")} tool={tool} ctx={scoped} onClose={onClose} /> : <div style={{ padding: 18, fontSize: 11.5, color: "var(--ink-4)" }}>panel unavailable</div>}
      </div>
    </div>
  );
}

Object.assign(window, { ToolWindow });

// src/app/tool-window/tool-window.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from "@angular/core";
import { Agent, Project } from "../models";
import { AgentRuntimeService } from "../agents/agent-runtime.service";
import { ProjectActionsService } from "../projects/project-actions.service";
import { IconComponent } from "../shared/icon.component";
import { BranchesPanelComponent } from "./branches-panel.component";
import { CommitGraphPanelComponent } from "./commit-graph-panel.component";
import { LocalHistoryPanelComponent } from "./local-history-panel.component";
import { TOOL_PANELS, ToolWindowStore } from "./tool-window.store";

/**
 * The IntelliJ-style bottom tool window (design toolwindow.jsx): a resizable
 * dock under the center content with a tab strip (accent underline), its own
 * project/worktree SCOPE — a tab can tile agents from several projects, so the
 * panels read from an explicit scope that by default FOLLOWS the focused agent
 * — and a close button. Closed by default; opened by the Git commands
 * (Ctrl+Shift+G / Ctrl+9 graph, Ctrl+Shift+B branches) or the palette.
 */
@Component({
  selector: "app-tool-window",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconComponent, CommitGraphPanelComponent, BranchesPanelComponent, LocalHistoryPanelComponent],
  template: `
    <!-- resize grip (absolute — sits over the top hairline) -->
    <div class="grip" (mousedown)="onGripDown($event)"></div>

    <!-- tab strip -->
    <div
      style="display:flex;align-items:stretch;gap:var(--sp-1);padding:0 var(--sp-4);border-bottom:1px solid var(--hair);flex:none;background:var(--panel-2)"
    >
      @for (p of panels; track p.kind) {
        @let on = p.kind === tw.panel();
        <button
          class="btn tab"
          (click)="tw.open(p.kind)"
          [style.color]="on ? 'var(--ink)' : 'var(--ink-3)'"
        >
          @if (on) { <span class="tab-line"></span> }
          <app-icon [name]="p.icon" size="sm" [color]="on ? 'var(--accent)' : null" />{{ p.label }}
        </button>
      }

      <!-- scope: project + worktree the panels act on -->
      <div style="margin-left:auto;display:flex;align-items:center;gap:var(--sp-3);padding-left:var(--sp-5)">
        <span class="up" style="font-size:var(--fs-3xs);color:var(--ink-4);flex:none">scope</span>
        @if (project(); as p) {
          <span style="display:flex;align-items:center;gap:var(--sp-2);flex:none">
            <app-icon [name]="p.icon" size="sm" [px]="12" [color]="p.color" />
            <select
              class="osel"
              title="Project the panels read from"
              [value]="p.id"
              (change)="pickProject($any($event.target).value)"
              style="width:152px;padding:var(--sp-1) var(--sp-9) var(--sp-1) var(--sp-4);font-size:var(--fs-xs)"
            >
              @for (pr of projects.all(); track pr.id) {
                <option [value]="pr.id">{{ pr.name }}</option>
              }
            </select>
          </span>
        }
        <select
          class="osel"
          title="Worktree the panel reads from"
          [value]="agent()?.id ?? ''"
          (change)="pickAgent($any($event.target).value)"
          style="width:150px;padding:var(--sp-1) var(--sp-9) var(--sp-1) var(--sp-4);font-size:var(--fs-xs);flex:none"
        >
          @if (!projAgents().length) { <option value="">no worktrees</option> }
          @for (a of projAgents(); track a.id) {
            <option [value]="a.id">{{ a.name }}</option>
          }
        </select>
        @if (outOfSync()) {
          <button
            class="btn ghost-hair follow"
            [title]="'Follow the focused agent · ' + focus()!.name"
            (click)="follow()"
          >
            <app-icon name="link" size="sm" [px]="11" />{{ focus()!.name }}
          </button>
        }
        <button class="pane-btn" (click)="tw.close()" title="Hide tool window" style="align-self:center">
          <app-icon name="x" size="sm" />
        </button>
      </div>
    </div>

    <!-- panel body -->
    <div style="flex:1;min-height:0;display:flex;flex-direction:column;background:var(--panel)">
      @switch (tw.panel()) {
        @case ('graph') { <app-commit-graph-panel [agent]="agent()" [project]="project()" /> }
        @case ('branches') { <app-branches-panel [agent]="agent()" [project]="project()" [agents]="projAgents()" /> }
        @case ('history') { <app-local-history-panel [agent]="agent()" /> }
      }
    </div>
  `,
  host: {
    "[style.height.px]": "h()",
  },
  styles: [
    `
      :host {
        position: relative;
        display: flex;
        flex-direction: column;
        min-height: 0;
        min-width: 0;
        flex: none;
        background: var(--panel);
        border-top: 1px solid var(--hair);
      }
      .grip {
        position: absolute;
        top: -2px;
        left: 0;
        right: 0;
        height: var(--sp-2);
        cursor: row-resize;
        z-index: 5;
      }
      .btn.tab {
        padding: var(--sp-3) var(--sp-5);
        border-radius: 0;
        position: relative;
        font-size: var(--fs-sm);
      }
      .tab-line {
        position: absolute;
        left: 8px;
        right: 8px;
        bottom: 0;
        height: var(--sp-1);
        background: linear-gradient(90deg, var(--accent), var(--accent-2));
      }
      .btn.follow {
        padding: var(--sp-1) var(--sp-3);
        font-size: var(--fs-xs);
        color: var(--accent-2);
        flex: none;
      }
    `,
  ],
})
export class ToolWindowComponent {
  readonly tw = inject(ToolWindowStore);
  readonly projects = inject(ProjectActionsService);
  readonly runtime = inject(AgentRuntimeService);

  readonly panels = TOOL_PANELS;

  // ---- dock height (design: 36vh clamped to [240, 420], drag-resizable) ----
  readonly h = signal(Math.round(Math.min(420, Math.max(240, window.innerHeight * 0.36))));

  onGripDown(e: MouseEvent): void {
    e.preventDefault();
    const startY = e.clientY;
    const startH = this.h();
    const move = (ev: MouseEvent) => {
      const next = startH + (startY - ev.clientY);
      this.h.set(Math.max(160, Math.min(window.innerHeight - 200, next)));
    };
    const up = () => {
      window.removeEventListener("mousemove", move);
      window.removeEventListener("mouseup", up);
      document.body.style.cursor = "";
    };
    window.addEventListener("mousemove", move);
    window.addEventListener("mouseup", up);
    document.body.style.cursor = "row-resize";
  }

  // ---- scope ----
  // null = follow the focused agent (the default); set by the two selects.
  private readonly explicit = signal<{ projectId: string | null; agentId: string | null }>({
    projectId: null,
    agentId: null,
  });

  /** The focused agent of the active tab (what the scope follows by default). */
  readonly focus = computed<Agent | null>(() => this.runtime.activeAgent());

  readonly project = computed<Project | undefined>(() => {
    const all = this.projects.all();
    const ex = this.explicit();
    return (
      (ex.projectId ? all.find((p) => p.id === ex.projectId) : undefined) ??
      all.find((p) => p.id === this.focus()?.projectId) ??
      all[0]
    );
  });

  readonly projAgents = computed<Agent[]>(() => {
    const p = this.project();
    return p ? this.runtime.agents().filter((a) => a.projectId === p.id) : [];
  });

  readonly agent = computed<Agent | null>(() => {
    const list = this.projAgents();
    const ex = this.explicit();
    return (
      (ex.agentId ? list.find((a) => a.id === ex.agentId) : undefined) ??
      list.find((a) => a.id === this.focus()?.id) ??
      list[0] ??
      null
    );
  });

  /** An explicit scope is set and it diverges from the focused agent. */
  readonly outOfSync = computed(() => {
    const f = this.focus();
    const ex = this.explicit();
    if (!f || (!ex.projectId && !ex.agentId)) return false;
    if (!this.projects.all().some((p) => p.id === f.projectId)) return false;
    return this.agent()?.id !== f.id;
  });

  pickProject(id: string): void {
    this.explicit.set({ projectId: id, agentId: null });
  }
  pickAgent(id: string): void {
    this.explicit.update((s) => ({ projectId: s.projectId ?? this.project()?.id ?? null, agentId: id || null }));
  }
  follow(): void {
    this.explicit.set({ projectId: null, agentId: null });
  }
}
